[package]
name = "rui_research"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { path = "../rust-sdl2-2.0.18", features = ["unsafe_textures"] }
glyph_brush = "0.7.7"
mopa = "0.2.2"